import Head from 'next/head';
import dynamic from 'next/dynamic';

const HomeComp = dynamic(() => import('../src/container/Home'));

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComp />
    </div>
  )
}
